// src/components/CopyButton.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    interface CopyButtonProps {
        id?: string;
        value: string;
        class?: string;
        children?: Snippet;
    }

    const { id, value, class: className, children }: CopyButtonProps = $props();

    let renderFeedback: boolean = $state(false);

    const copyValue = () => {
        navigator.clipboard.writeText(value);
        renderFeedback = true;

        return setTimeout(() => renderFeedback = false, 5000);
    };
</script>

<button
    id={id} 
    onclick={copyValue}
    title={`Copy '${value}'`}
    class={["relative cursor-pointer", className]}
>
    {#if renderFeedback}
        <span
            role="presentation"
            class="flex items-center gap-1 bg-success-600 rounded absolute top-4 right-4 px-3 py-0.5 text-sm font-semibold"
        >
            <i class="i bi-check-lg"></i>
            <span>Copied!&nbsp;</span>
        </span>
    {/if}
    {@render children?.()}
</button>

// src/components/CopyButton.tsx
"use client";
import { JSX, ReactNode, useState } from "react";

export default function CopyButton({
    id,
    value,
    className,
    children
}: CopyButtonProps): JSX.Element {
    const [renderFeedback, setRenderFeedback] = useState<boolean>(false);
    const copyValue = () => {
        navigator.clipboard.writeText(value);
        setRenderFeedback(true);

        return setTimeout(() => setRenderFeedback(false), 5000);
    };
    return (
        <button
            id={id} 
            onClick={copyValue}
            title={`Copy '${value}'`}
            className={`${className} relative cursor-pointer`}
        >
            {renderFeedback &&
                <span
                    role="presentation"
                    className="flex items-center gap-1 bg-success-600 rounded absolute top-4 right-4 px-3 py-0.5 text-sm font-semibold"
                    
                >
                    <i className="i bi-check-lg"></i>
                    <span>Copied!&nbsp;</span>
                </span>
            }
            {children}
        </button>
    );
}

export interface CopyButtonProps {
    id?: string;
    value: string;
    className?: string;
    children?: ReactNode;
}
